### Read AS data

In [16]:
import pandas as pd

file_path = 'ensembl.txt'
dat = pd.read_csv(file_path)  # Specify the delimiter if it's not a comma-separated file

dat.head(20)

,seqname,source,feature,start,end,score,strand,frame,hid,hstart,hend,genscan,gene_id,transcript_id,exon_id,gene_type,variation_name,probe_name
0,1,Ensembl,similarity,55039733,55040044,1051,+,.,H2N797.2,85.0,186.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Ensembl,similarity,55039838,55040044,921,+,.,B4DEZ9.1,1.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Ensembl,similarity,55039838,55040044,787,+,.,F7BM04.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Ensembl,similarity,55039838,55040044,893,+,.,G3S2C5.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Ensembl,similarity,55039838,55040044,891,+,.,K7B7Q7.1,1.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,Ensembl,similarity,55039838,55040044,893,+,.,A8T650.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,Ensembl,similarity,55039838,55040044,902,+,.,K7BKH3.1,1.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,Ensembl,similarity,55039838,55040044,689,+,.,L9KYI8.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,Ensembl,similarity,55039838,55040044,576,+,.,Q80W65.2,1.0,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,Ensembl,similarity,55039838,55040044,875,+,.,A8T658.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1,Ensembl,similarity,55039838,55040044,912,+,.,Q8NBP7.3,1.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1,Ensembl,similarity,55039838,55040044,579,+,.,H0VTV9.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1,Ensembl,similarity,55039838,55040044,907,+,.,A8T655.2,1.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1,Ensembl,similarity,55039838,55040044,696,+,.,I3LGB2.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1,Ensembl,similarity,55039838,55040044,688,+,.,I3M601.1,1.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1,Ensembl,similarity,55039838,55040044,912,+,.,A8T644.1,1.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1,Ensembl,similarity,55039838,55040044,806,+,.,G3QLV4.1,1.0,56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1,Ensembl,similarity,55039862,55040044,561,+,.,P59996.1,7.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1,Ensembl,similarity,55039868,55040044,447,+,.,H3AN22.1,5.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1,Ensembl,similarity,55039982,55040044,308,+,.,H2L850.1,1.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
dat.tail(20)

,seqname,source,feature,start,end,score,strand,frame,hid,hstart,hend,genscan,gene_id,transcript_id,exon_id,gene_type,variation_name,probe_name
8445,1,Ensembl,gene,55063369,55064852,.,+,0,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-NM_174936.4.1,exon-NM_174936.4-12,protein_coding,NaN,NaN
8446,1,Ensembl,gene,55056261,55056805,.,+,-1,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-XM_047417050.1.1,exon-XM_047417050.1-1,protein_coding,NaN,NaN
8447,1,Ensembl,gene,55057331,55057514,.,+,0,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-XM_047417050.1.1,exon-NM_174936.4-7,protein_coding,NaN,NaN
8448,1,Ensembl,gene,55058036,55058209,.,+,1,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-XM_047417050.1.1,exon-NM_174936.4-8,protein_coding,NaN,NaN
8449,1,Ensembl,gene,55058499,55058647,.,+,1,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-XM_047417050.1.1,exon-NM_174936.4-9,protein_coding,NaN,NaN
8450,1,Ensembl,gene,55059486,55059663,.,+,0,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-XM_047417050.1.1,exon-NM_174936.4-10,protein_coding,NaN,NaN
8451,1,Ensembl,gene,55061375,55061556,.,+,1,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-XM_047417050.1.1,exon-NM_174936.4-11,protein_coding,NaN,NaN
8452,1,Ensembl,gene,55063369,55064852,.,+,0,NaN,NaN,NaN,NaN,gene-PCSK9.1,rna-XM_047417050.1.1,exon-NM_174936.4-12,protein_coding,NaN,NaN
8453,1,Ensembl,gene,55039838,55040044,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.11,ccds_gene,NaN,NaN
8454,1,Ensembl,gene,55043843,55044034,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.12,ccds_gene,NaN,NaN
8455,1,Ensembl,gene,55046523,55046646,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.13,ccds_gene,NaN,NaN
8456,1,Ensembl,gene,55052278,55052411,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.14,ccds_gene,NaN,NaN
8457,1,Ensembl,gene,55052650,55052791,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.15,ccds_gene,NaN,NaN
8458,1,Ensembl,gene,55055993,55056189,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.16,ccds_gene,NaN,NaN
8459,1,Ensembl,gene,55057331,55057514,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.17,ccds_gene,NaN,NaN
8460,1,Ensembl,gene,55058036,55058209,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.18,ccds_gene,NaN,NaN
8461,1,Ensembl,gene,55058499,55058647,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.19,ccds_gene,NaN,NaN
8462,1,Ensembl,gene,55059486,55059663,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.110,ccds_gene,NaN,NaN
8463,1,Ensembl,gene,55061375,55061556,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.111,ccds_gene,NaN,NaN
8464,1,Ensembl,gene,55063369,55063584,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.112,ccds_gene,NaN,NaN

### subset non-coding variant coordinates and with gene ID PCSK9

In [18]:
df = dat[dat['gene_type'] != "protein_coding"].copy()

In [19]:
df.head(20)

,seqname,source,feature,start,end,score,strand,frame,hid,hstart,hend,genscan,gene_id,transcript_id,exon_id,gene_type,variation_name,probe_name
0,1,Ensembl,similarity,55039733,55040044,1051,+,.,H2N797.2,85.0,186.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Ensembl,similarity,55039838,55040044,921,+,.,B4DEZ9.1,1.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Ensembl,similarity,55039838,55040044,787,+,.,F7BM04.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Ensembl,similarity,55039838,55040044,893,+,.,G3S2C5.1,1.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Ensembl,similarity,55039838,55040044,891,+,.,K7B7Q7.1,1.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8460,1,Ensembl,gene,55058036,55058209,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.18,ccds_gene,NaN,NaN
8461,1,Ensembl,gene,55058499,55058647,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.19,ccds_gene,NaN,NaN
8462,1,Ensembl,gene,55059486,55059663,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.110,ccds_gene,NaN,NaN
8463,1,Ensembl,gene,55061375,55061556,.,+,1,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.111,ccds_gene,NaN,NaN
8464,1,Ensembl,gene,55063369,55063584,.,+,0,NaN,NaN,NaN,NaN,CCDS603.1.1,CCDS603.1.1,CCDS603.112,ccds_gene,NaN,NaN

## Read gnomAD PCSK9 gene variants data

In [24]:
import csv

filename = 'gnomAD_v2.1.1_ENSG00000169174_2023_09_21_22_52_39.csv'

# Read the CSV file into a DataFrame
gf = pd.read_csv(filename)

# Display the first few rows of the DataFrame
print(gf[['Chromosome', 'Position', 'rsIDs', 'Transcript']].head(20))

    Chromosome  Position         rsIDs         Transcript
0            1  55505447    rs45448095  ENST00000302118.5
1            1  55505452   rs576575389  ENST00000302118.5
2            1  55505457   rs545454601  ENST00000302118.5
3            1  55505457   rs545454601  ENST00000302118.5
4            1  55505462  rs1043549074  ENST00000302118.5
5            1  55505463  rs1193796116  ENST00000302118.5
6            1  55505464  rs1269395517  ENST00000302118.5
7            1  55505466  rs1365420733  ENST00000302118.5
8            1  55505469  rs1473950917  ENST00000302118.5
9            1  55505477   rs576535214  ENST00000302118.5
10           1  55505482  rs1389098623  ENST00000302118.5
11           1  55505483   rs376542717  ENST00000302118.5
12           1  55505485    rs28362202  ENST00000302118.5
13           1  55505488  rs1393600693  ENST00000302118.5
14           1  55505489  rs1387827816  ENST00000302118.5
15           1  55505499   rs182393980  ENST00000302118.5
16           1  55505500  rs1298619732  ENST00000302118.5
17           1  55505501  rs1341655436  ENST00000302118.5
18           1  55505503   rs886039837  ENST00000302118.5
19           1  55505507  rs1357021576  ENST00000302118.5

### Merge AS data with gnomAD PCSK9 gene variants based on the Position

In [ ]:
import pandas as pd

# Sample data
data1 = gf
df1 = pd.DataFrame(data1)

data2 = df
df2 = pd.DataFrame(data2)


# List to store merged rows
merged_rows = []

# Loop through each row in df1 and df2
for index1, row1 in df1.iterrows():
    for index2, row2 in df2.iterrows():
        if row2['start'] <= row1['Position'] <= row2['end']:
            # Combine the rows
            combined_row = row1.to_dict()
            combined_row.update(row2.to_dict())
            merged_rows.append(combined_row)

# Convert merged rows to DataFrame
merged_df = pd.DataFrame(merged_rows)

merged_df[['Position', 'start', 'end']]

print(merged_df)